{% set name = "django-robots" %}
{% set version = "5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-robots-{{ version }}.tar.gz
  sha256: f5817975a9e3b082440a81396111d8a6671b54f6aa11349847554bd1beebd959

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - python >=3.6
    - django >=1.11,<3.0


test:
  imports:
    - robots
    - robots.migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-robots/
  summary: Robots exclusion application for Django, complementing Sitemaps.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
